export const GET_BOOK_LIST_SUCCESS = 'GET_BOOK_LIST_SUCCESS';
export const GET_BOOK_LIST = 'GET_BOOK_LIST';
export const CREATE_BOOK = 'CREATE_BOOK';
export const TOGGLE_CREATE_BOOK = 'TOGGLE_CREATE_BOOK';
